dataset <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE)
dataset$DateTime <- strptime(paste(dataset$Date, dataset$Time), format="%d/%m/%Y %H:%M:%S")
dataset$Global_active_power = as.numeric(as.character(dataset$Global_active_power))
dataset$Date <- as.Date(dataset$Date, "%d/%m/%Y")
dataset$weekdays <- weekdays(dataset$Date)
datasubset <- subset(dataset, dataset$Date >= "2007-02-01" & dataset$Date <= "2007-02-02")
png("Plot2.png", width = 480, height = 480)
plot(datasubset$DateTime, datasubset$Global_active_power, type= 'n',xlab = "", ylab = "Global Active Power(kilowatts)")
lines(datasubset$DateTime, datasubset$Global_active_power)
dev.off()