dataset <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE)
dataset$DateTime <- strptime(paste(dataset$Date, dataset$Time), format="%d/%m/%Y %H:%M:%S")
dataset$Global_active_power = as.numeric(as.character(dataset$Global_active_power))
dataset$Sub_metering_1 = as.numeric(as.character(dataset$Sub_metering_1))
dataset$Sub_metering_2 = as.numeric(as.character(dataset$Sub_metering_2))
dataset$Sub_metering_3 = as.numeric(as.character(dataset$Sub_metering_3))

dataset$Date <- as.Date(dataset$Date, "%d/%m/%Y")
dataset$weekdays <- weekdays(dataset$Date)
datasubset <- subset(dataset, dataset$Date >= "2007-02-01" & dataset$Date <= "2007-02-02")
png("Plot3.png", width = 480, height = 480)
plot(datasubset$DateTime, datasubset$Sub_metering_1, type= 'n',xlab = "", ylab = "Energy Sub Metering")
lines(datasubset$DateTime, datasubset$Sub_metering_1)
lines(datasubset$DateTime, datasubset$Sub_metering_2, col = "red")
lines(datasubset$DateTime, datasubset$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub metering 1", "Sub metering 2", "Sub metering 3"), col = c("black", "red", "blue"), lty = 1)
dev.off()
